export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
export const LOAD_ACCOUNTS_FAILURE = 'LOAD_ACCOUNTS_FAILURE';
export const LOAD_ACCOUNTS_SUCCESS = 'LOAD_ACCOUNTS_SUCCESS';
export const CHANGE_ACCOUNT_TITLE = 'CHANGE_ACCOUNT_TITLE';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const REMOVE_EXTERNAL_ACCOUNT = 'REMOVE_EXTERNAL_ACCOUNT';
